apiVersion: v1
items:
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: default
  spec:
    limits:
    - max:
        cpu: "1"
        memory: 1Gi
      type: Pod
    - default:
        cpu: "1"
        memory: 2Gi
      defaultRequest:
        cpu: 20m
        memory: 20Mi
      type: Container
    - max:
        storage: 10Gi
      type: PersistentVolumeClaim
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

